name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # I changed this from 3.9.2 to 3.0.0 to ensure it works on your machine.
  # This allows any Dart version from 3.0 up to (but not including) 4.0.
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Networking & Data
  signalr_netcore: ^1.3.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # UI & Fonts
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3

  # Web Support
  flutter_web_plugins:
    sdk: flutter
  firebase_messaging: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg